///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FirstTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FirstTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("194c01c2-c2bb-4ee8-aeee-f4a422e2b6e3")]
    public partial class FirstTest1Repository : RepoGenBaseFolder
    {
        static FirstTest1Repository instance = new FirstTest1Repository();
        FirstTest1RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the FirstTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("194c01c2-c2bb-4ee8-aeee-f4a422e2b6e3")]
        public static FirstTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FirstTest1Repository() 
            : base("FirstTest1Repository", "/", null, 0, false, "194c01c2-c2bb-4ee8-aeee-f4a422e2b6e3", ".\\RepositoryImages\\FirstTest1Repository194c01c2.rximgres")
        {
            _applicationundertest = new FirstTest1RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("194c01c2-c2bb-4ee8-aeee-f4a422e2b6e3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("964f60bb-9366-4ec6-a109-301c1ba39b78")]
        public virtual FirstTest1RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FirstTest1RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("964f60bb-9366-4ec6-a109-301c1ba39b78")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxstudiologoInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "964f60bb-9366-4ec6-a109-301c1ba39b78", "")
            {
                _rxstudiologoInfo = new RepoItemInfo(this, "RxStudioLogo", "?/?/tabpage[@controlname='RxTabIntroduction']/picture[@controlname='RxStudioLogo']", 30000, null, "f4e78049-69be-436f-952c-1bcd618c0581");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", 30000, null, "1c0e8023-e711-4c5a-9305-17cc732e6403");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("964f60bb-9366-4ec6-a109-301c1ba39b78")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("964f60bb-9366-4ec6-a109-301c1ba39b78")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxStudioLogo item.
            /// </summary>
            [RepositoryItem("f4e78049-69be-436f-952c-1bcd618c0581")]
            public virtual Ranorex.Picture RxStudioLogo
            {
                get
                {
                    return _rxstudiologoInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The RxStudioLogo item info.
            /// </summary>
            [RepositoryItemInfo("f4e78049-69be-436f-952c-1bcd618c0581")]
            public virtual RepoItemInfo RxStudioLogoInfo
            {
                get
                {
                    return _rxstudiologoInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("1c0e8023-e711-4c5a-9305-17cc732e6403")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("1c0e8023-e711-4c5a-9305-17cc732e6403")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
