///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d32382c6-cbd1-4bd5-a7d3-451260cce983")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("d32382c6-cbd1-4bd5-a7d3-451260cce983")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "d32382c6-cbd1-4bd5-a7d3-451260cce983", ".\\RepositoryImages\\MyTestRepositoryd32382c6.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d32382c6-cbd1-4bd5-a7d3-451260cce983")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("1bccd1b0-cd1e-47f2-85b0-09be9554960f")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("1bccd1b0-cd1e-47f2-85b0-09be9554960f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _divtagproduseInfo;
            RepoItemInfo _pcperifericesoftwareInfo;
            RepoItemInfo _desktoppcInfo;
            RepoItemInfo _instocInfo;
            RepoItemInfo _emagInfo;
            RepoItemInfo _desktopgaminglenovolegionc53019icbInfo;
            RepoItemInfo _atagreviewInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.emag.ro']", parentFolder, 30000, null, true, "1bccd1b0-cd1e-47f2-85b0-09be9554960f", "")
            {
                _divtagproduseInfo = new RepoItemInfo(this, "DivTagPRODUSE", ".//nav[#'auxiliary']/?/?/div/ul[1]/?/?/div[@innertext~'^\\ PRODUSE\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "ab8e7d43-771b-45a1-9350-26b12dd4418f");
                _pcperifericesoftwareInfo = new RepoItemInfo(this, "PCPerifericeSoftware", "body/div[3]/div[1]//ul/li[2]/?/?/span[@innertext='PC, Periferice & Software']", 30000, null, "b558f1c2-c4f3-4b8c-a354-eefff2e5be76");
                _desktoppcInfo = new RepoItemInfo(this, "DesktopPC", "body/div[3]/div[1]/div/div[2]/div[2]/?/?/ul/li[1]/div[1]/a[@innertext='Desktop PC']", 30000, null, "3fdc87a1-3c27-4f8c-86a5-df59b09977cd");
                _instocInfo = new RepoItemInfo(this, "InStoc", ".//div[#'page-skin']/div[2]/div/div[3]/div[1]/div[2]/div[2]/div[1]//a[@innertext='In Stoc ']", 30000, null, "49d9d285-8180-4c7e-a9e0-c1187e3a3d92");
                _emagInfo = new RepoItemInfo(this, "EMAG", ".//div[#'page-skin']/div[2]/div/div[3]/div[1]/div[2]/div[2]/div[20]//a[@innertext='eMAG ']", 30000, null, "04221bb4-ee9b-4403-b2b7-c9b53577943d");
                _desktopgaminglenovolegionc53019icbInfo = new RepoItemInfo(this, "DesktopGamingLenovoLegionC53019ICB", ".//div[#'card_grid']/div[1]/div/div/div[1]/div[1]//img[@alt~'^Desktop\\ Gaming\\ Lenovo\\ Leg']", 30000, null, "dcbe22c0-f21f-41bf-aa65-e018d07a6515");
                _atagreviewInfo = new RepoItemInfo(this, "ATagReview", ".//ul[#'product_navbar_sticky']/li[3]/a[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "c978ffe0-7f20-4ac5-89f4-03f00e6d16c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1bccd1b0-cd1e-47f2-85b0-09be9554960f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1bccd1b0-cd1e-47f2-85b0-09be9554960f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DivTagPRODUSE item.
            /// </summary>
            [RepositoryItem("ab8e7d43-771b-45a1-9350-26b12dd4418f")]
            public virtual Ranorex.DivTag DivTagPRODUSE
            {
                get
                {
                    return _divtagproduseInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagPRODUSE item info.
            /// </summary>
            [RepositoryItemInfo("ab8e7d43-771b-45a1-9350-26b12dd4418f")]
            public virtual RepoItemInfo DivTagPRODUSEInfo
            {
                get
                {
                    return _divtagproduseInfo;
                }
            }

            /// <summary>
            /// The PCPerifericeSoftware item.
            /// </summary>
            [RepositoryItem("b558f1c2-c4f3-4b8c-a354-eefff2e5be76")]
            public virtual Ranorex.SpanTag PCPerifericeSoftware
            {
                get
                {
                    return _pcperifericesoftwareInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PCPerifericeSoftware item info.
            /// </summary>
            [RepositoryItemInfo("b558f1c2-c4f3-4b8c-a354-eefff2e5be76")]
            public virtual RepoItemInfo PCPerifericeSoftwareInfo
            {
                get
                {
                    return _pcperifericesoftwareInfo;
                }
            }

            /// <summary>
            /// The DesktopPC item.
            /// </summary>
            [RepositoryItem("3fdc87a1-3c27-4f8c-86a5-df59b09977cd")]
            public virtual Ranorex.ATag DesktopPC
            {
                get
                {
                    return _desktoppcInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DesktopPC item info.
            /// </summary>
            [RepositoryItemInfo("3fdc87a1-3c27-4f8c-86a5-df59b09977cd")]
            public virtual RepoItemInfo DesktopPCInfo
            {
                get
                {
                    return _desktoppcInfo;
                }
            }

            /// <summary>
            /// The InStoc item.
            /// </summary>
            [RepositoryItem("49d9d285-8180-4c7e-a9e0-c1187e3a3d92")]
            public virtual Ranorex.ATag InStoc
            {
                get
                {
                    return _instocInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The InStoc item info.
            /// </summary>
            [RepositoryItemInfo("49d9d285-8180-4c7e-a9e0-c1187e3a3d92")]
            public virtual RepoItemInfo InStocInfo
            {
                get
                {
                    return _instocInfo;
                }
            }

            /// <summary>
            /// The EMAG item.
            /// </summary>
            [RepositoryItem("04221bb4-ee9b-4403-b2b7-c9b53577943d")]
            public virtual Ranorex.ATag EMAG
            {
                get
                {
                    return _emagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EMAG item info.
            /// </summary>
            [RepositoryItemInfo("04221bb4-ee9b-4403-b2b7-c9b53577943d")]
            public virtual RepoItemInfo EMAGInfo
            {
                get
                {
                    return _emagInfo;
                }
            }

            /// <summary>
            /// The DesktopGamingLenovoLegionC53019ICB item.
            /// </summary>
            [RepositoryItem("dcbe22c0-f21f-41bf-aa65-e018d07a6515")]
            public virtual Ranorex.ImgTag DesktopGamingLenovoLegionC53019ICB
            {
                get
                {
                    return _desktopgaminglenovolegionc53019icbInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The DesktopGamingLenovoLegionC53019ICB item info.
            /// </summary>
            [RepositoryItemInfo("dcbe22c0-f21f-41bf-aa65-e018d07a6515")]
            public virtual RepoItemInfo DesktopGamingLenovoLegionC53019ICBInfo
            {
                get
                {
                    return _desktopgaminglenovolegionc53019icbInfo;
                }
            }

            /// <summary>
            /// The ATagReview item.
            /// </summary>
            [RepositoryItem("c978ffe0-7f20-4ac5-89f4-03f00e6d16c3")]
            public virtual Ranorex.ATag ATagReview
            {
                get
                {
                    return _atagreviewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagReview item info.
            /// </summary>
            [RepositoryItemInfo("c978ffe0-7f20-4ac5-89f4-03f00e6d16c3")]
            public virtual RepoItemInfo ATagReviewInfo
            {
                get
                {
                    return _atagreviewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
