///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ThirdTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ThirdTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6f57987c-90f8-49b7-a522-c5bd8451ffbd")]
    public partial class ThirdTestRepository : RepoGenBaseFolder
    {
        static ThirdTestRepository instance = new ThirdTestRepository();
        ThirdTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the ThirdTestRepository element repository.
        /// </summary>
        [RepositoryFolder("6f57987c-90f8-49b7-a522-c5bd8451ffbd")]
        public static ThirdTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ThirdTestRepository() 
            : base("ThirdTestRepository", "/", null, 0, false, "6f57987c-90f8-49b7-a522-c5bd8451ffbd", ".\\RepositoryImages\\ThirdTestRepository6f57987c.rximgres")
        {
            _applicationundertest = new ThirdTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6f57987c-90f8-49b7-a522-c5bd8451ffbd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("854dd850-c40e-44da-8cb1-d00f0e259f55")]
        public virtual ThirdTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ThirdTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("854dd850-c40e-44da-8cb1-d00f0e259f55")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectpoweredbygarminInfo;
            RepoItemInfo _signinInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _loginbtnsigninInfo;
            RepoItemInfo _andreisavoiuInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='connect.garmin.com']", parentFolder, 30000, null, true, "854dd850-c40e-44da-8cb1-d00f0e259f55", "")
            {
                _connectpoweredbygarminInfo = new RepoItemInfo(this, "ConnectPoweredByGarmin", ".//div[#'global-header-wrapper']//a[@innertext='Garmin Connect']", 30000, null, "f84b9dcb-c6f7-4dae-bd35-f501e33b1eb4");
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//div[#'global-header-wrapper']/div/div[2]/ul/?/?/a[@innertext='Sign In']", 30000, null, "99bb516f-8c65-48d9-b8d7-c690b2e7c031");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//iframe[#'gauth-widget-frame-gauth-widget']//input[#'username']", 30000, null, "163a84a9-f06e-4cb1-b027-2b838a9e0ca6");
                _loginbtnsigninInfo = new RepoItemInfo(this, "LoginBtnSignin", ".//iframe[#'gauth-widget-frame-gauth-widget']//button[#'login-btn-signin']", 30000, null, "eae2362f-bd72-4e85-966f-c1e334ba1998");
                _andreisavoiuInfo = new RepoItemInfo(this, "AndreiSavoiu", "body/div[1]/div[3]/header/div[2]/div[4]/a[@href~'^https://connect\\.garmin\\.co']/img[@alt='Andrei.Savoiu']", 30000, null, "e754fe05-966c-4639-b828-7398c094c033");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("854dd850-c40e-44da-8cb1-d00f0e259f55")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("854dd850-c40e-44da-8cb1-d00f0e259f55")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConnectPoweredByGarmin item.
            /// </summary>
            [RepositoryItem("f84b9dcb-c6f7-4dae-bd35-f501e33b1eb4")]
            public virtual Ranorex.ATag ConnectPoweredByGarmin
            {
                get
                {
                    return _connectpoweredbygarminInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ConnectPoweredByGarmin item info.
            /// </summary>
            [RepositoryItemInfo("f84b9dcb-c6f7-4dae-bd35-f501e33b1eb4")]
            public virtual RepoItemInfo ConnectPoweredByGarminInfo
            {
                get
                {
                    return _connectpoweredbygarminInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("99bb516f-8c65-48d9-b8d7-c690b2e7c031")]
            public virtual Ranorex.ATag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("99bb516f-8c65-48d9-b8d7-c690b2e7c031")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("163a84a9-f06e-4cb1-b027-2b838a9e0ca6")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("163a84a9-f06e-4cb1-b027-2b838a9e0ca6")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The LoginBtnSignin item.
            /// </summary>
            [RepositoryItem("eae2362f-bd72-4e85-966f-c1e334ba1998")]
            public virtual Ranorex.ButtonTag LoginBtnSignin
            {
                get
                {
                    return _loginbtnsigninInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginBtnSignin item info.
            /// </summary>
            [RepositoryItemInfo("eae2362f-bd72-4e85-966f-c1e334ba1998")]
            public virtual RepoItemInfo LoginBtnSigninInfo
            {
                get
                {
                    return _loginbtnsigninInfo;
                }
            }

            /// <summary>
            /// The AndreiSavoiu item.
            /// </summary>
            [RepositoryItem("e754fe05-966c-4639-b828-7398c094c033")]
            public virtual Ranorex.ImgTag AndreiSavoiu
            {
                get
                {
                    return _andreisavoiuInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The AndreiSavoiu item info.
            /// </summary>
            [RepositoryItemInfo("e754fe05-966c-4639-b828-7398c094c033")]
            public virtual RepoItemInfo AndreiSavoiuInfo
            {
                get
                {
                    return _andreisavoiuInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
