///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FirstTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FirstTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("aee1f048-69bb-47c1-8e33-5138d124d1d0")]
    public partial class FirstTestRepository : RepoGenBaseFolder
    {
        static FirstTestRepository instance = new FirstTestRepository();
        FirstTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the FirstTestRepository element repository.
        /// </summary>
        [RepositoryFolder("aee1f048-69bb-47c1-8e33-5138d124d1d0")]
        public static FirstTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FirstTestRepository() 
            : base("FirstTestRepository", "/", null, 0, false, "aee1f048-69bb-47c1-8e33-5138d124d1d0", ".\\RepositoryImages\\FirstTestRepositoryaee1f048.rximgres")
        {
            _applicationundertest = new FirstTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("aee1f048-69bb-47c1-8e33-5138d124d1d0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("0981e0cf-bdfb-4cd9-ab2e-087ea995e667")]
        public virtual FirstTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FirstTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("0981e0cf-bdfb-4cd9-ab2e-087ea995e667")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxwelcometext1Info;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "0981e0cf-bdfb-4cd9-ab2e-087ea995e667", "")
            {
                _rxwelcometext1Info = new RepoItemInfo(this, "RxWelcomeText1", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='RxWelcomeText1']", 30000, null, "98f403d7-967e-42be-be49-7e04c8ce4c31");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", 30000, null, "b57d4f82-6ebd-495f-b51f-ebeaae779c1a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0981e0cf-bdfb-4cd9-ab2e-087ea995e667")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0981e0cf-bdfb-4cd9-ab2e-087ea995e667")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxWelcomeText1 item.
            /// </summary>
            [RepositoryItem("98f403d7-967e-42be-be49-7e04c8ce4c31")]
            public virtual Ranorex.Text RxWelcomeText1
            {
                get
                {
                    return _rxwelcometext1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RxWelcomeText1 item info.
            /// </summary>
            [RepositoryItemInfo("98f403d7-967e-42be-be49-7e04c8ce4c31")]
            public virtual RepoItemInfo RxWelcomeText1Info
            {
                get
                {
                    return _rxwelcometext1Info;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("b57d4f82-6ebd-495f-b51f-ebeaae779c1a")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("b57d4f82-6ebd-495f-b51f-ebeaae779c1a")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
