///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SecondTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SecondTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("95c86ef8-3525-4b00-88f0-16d54a3f3f84")]
    public partial class SecondTestRepository : RepoGenBaseFolder
    {
        static SecondTestRepository instance = new SecondTestRepository();
        SecondTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the SecondTestRepository element repository.
        /// </summary>
        [RepositoryFolder("95c86ef8-3525-4b00-88f0-16d54a3f3f84")]
        public static SecondTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SecondTestRepository() 
            : base("SecondTestRepository", "/", null, 0, false, "95c86ef8-3525-4b00-88f0-16d54a3f3f84", ".\\RepositoryImages\\SecondTestRepository95c86ef8.rximgres")
        {
            _applicationundertest = new SecondTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("95c86ef8-3525-4b00-88f0-16d54a3f3f84")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("11d44127-8704-401e-8ea2-78cdde221bb9")]
        public virtual SecondTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SecondTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("11d44127-8704-401e-8ea2-78cdde221bb9")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _brandingInfo;
            RepoItemInfo _atagloginInfo;
            RepoItemInfo _atagloginusingfacebookInfo;
            RepoItemInfo _andreisăvoiuInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.strava.com']", parentFolder, 30000, null, true, "11d44127-8704-401e-8ea2-78cdde221bb9", "")
            {
                _brandingInfo = new RepoItemInfo(this, "Branding", ".//div[#'view']/header/div/div/div", 30000, null, "d3635c57-4e22-42e7-9c90-97f224af1d7c");
                _atagloginInfo = new RepoItemInfo(this, "ATagLogIn", ".//div[#'view']//nav/a[@innertext='Log In']", 30000, null, "e7d63223-ae0e-4bc3-983e-1cf02ef30d31");
                _atagloginusingfacebookInfo = new RepoItemInfo(this, "ATagLogInUsingFacebook", ".//form[#'login_form']/?/?/a[@innertext='Log in using Facebook']", 30000, null, "21d3814a-561b-4e66-8445-7dfbcfa938d0");
                _andreisăvoiuInfo = new RepoItemInfo(this, "AndreiSăvoiu", ".//div[#'athlete-profile']/div[1]/a[@href~'^https://www\\.strava\\.com/at']//img[@alt='Andrei Săvoiu']", 30000, null, "8739a86c-6dc3-49b9-9e1d-58c390db0746");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("11d44127-8704-401e-8ea2-78cdde221bb9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("11d44127-8704-401e-8ea2-78cdde221bb9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Branding item.
            /// </summary>
            [RepositoryItem("d3635c57-4e22-42e7-9c90-97f224af1d7c")]
            public virtual Ranorex.DivTag Branding
            {
                get
                {
                    return _brandingInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Branding item info.
            /// </summary>
            [RepositoryItemInfo("d3635c57-4e22-42e7-9c90-97f224af1d7c")]
            public virtual RepoItemInfo BrandingInfo
            {
                get
                {
                    return _brandingInfo;
                }
            }

            /// <summary>
            /// The ATagLogIn item.
            /// </summary>
            [RepositoryItem("e7d63223-ae0e-4bc3-983e-1cf02ef30d31")]
            public virtual Ranorex.ATag ATagLogIn
            {
                get
                {
                    return _atagloginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagLogIn item info.
            /// </summary>
            [RepositoryItemInfo("e7d63223-ae0e-4bc3-983e-1cf02ef30d31")]
            public virtual RepoItemInfo ATagLogInInfo
            {
                get
                {
                    return _atagloginInfo;
                }
            }

            /// <summary>
            /// The ATagLogInUsingFacebook item.
            /// </summary>
            [RepositoryItem("21d3814a-561b-4e66-8445-7dfbcfa938d0")]
            public virtual Ranorex.ATag ATagLogInUsingFacebook
            {
                get
                {
                    return _atagloginusingfacebookInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagLogInUsingFacebook item info.
            /// </summary>
            [RepositoryItemInfo("21d3814a-561b-4e66-8445-7dfbcfa938d0")]
            public virtual RepoItemInfo ATagLogInUsingFacebookInfo
            {
                get
                {
                    return _atagloginusingfacebookInfo;
                }
            }

            /// <summary>
            /// The AndreiSăvoiu item.
            /// </summary>
            [RepositoryItem("8739a86c-6dc3-49b9-9e1d-58c390db0746")]
            public virtual Ranorex.ImgTag AndreiSăvoiu
            {
                get
                {
                    return _andreisăvoiuInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The AndreiSăvoiu item info.
            /// </summary>
            [RepositoryItemInfo("8739a86c-6dc3-49b9-9e1d-58c390db0746")]
            public virtual RepoItemInfo AndreiSăvoiuInfo
            {
                get
                {
                    return _andreisăvoiuInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
